TiagoDvl/Teira

app/src/main/java/br/com/tick/teira/ui/screens/wallet/ExpensesGrid.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/viewmodels/ExpensesGridViewModel.kt
We shouldn't have to have all that machinery in order to consume a flow.
Having that on a single line is so much better for ever growing VM.
=> 4 - Changing Flow Strategy

app/src/main/java/br/com/tick/teira/ui/datasource/databases/ExpenseDao.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpenseRepository.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpensesRepositoryImpl.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/ExpensesGrid.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/QuickExpenseBar.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/WalletScreen.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/viewmodels/ExpensesGridViewModel.kt
- The elements displayed at the center should display cards with information
- They are limited to 12 on this screen
- The flow is working so amazingly well (I'm so happy ATM)
=> 5 - Enhance Expense Cards

app/src/main/java/br/com/tick/teira/ui/datasource/databases/TeiraDatabase.kt, app/src/main/java/br/com/tick/teira/ui/datasource/databases/entities/Expense.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpenseRepository.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpensesRepositoryImpl.kt, app/src/main/java/br/com/tick/teira/ui/di/DatabaseModule.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/QuickExpenseBar.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/viewmodels/QuickExpenseBarViewModel.kt
- We will use dates to work on some analytics logics
- We have to find a way to add an "Advanced" expense with more fields or to create an edit/deletion.
=> [9] - Added dates and indications to expense

app/src/main/java/br/com/tick/teira/shared/dispatchers/DefaultDispatcherProvider.kt, app/src/main/java/br/com/tick/teira/shared/dispatchers/DispatcherProvider.kt, app/src/main/java/br/com/tick/teira/ui/datasource/databases/ExpenseDao.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpenseRepository.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpensesRepositoryImpl.kt, app/src/main/java/br/com/tick/teira/ui/di/DispatchersProvider.kt, app/src/main/java/br/com/tick/teira/ui/screens/elements/FlipCard.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/ExpensesGrid.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/models/ExpenseCard.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/states/ExpensesGridStates.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/usecases/CreateExpensesCards.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/usecases/RemoveExpenseCard.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/viewmodels/ExpensesGridViewModel.kt, app/src/main/res/drawable/ic_delete.xml, app/src/main/res/drawable/ic_edit.xml, app/src/main/res/drawable/ic_flip.xml
- Learned a lot about stateless composes and positions on the grid.
- This component looks super cool.
- Still have to update the colors everything look ugly.
=> [10] - Adding flip card feature

app/src/main/java/br/com/tick/teira/MainActivity.kt, app/src/main/java/br/com/tick/teira/ui/elements/FlipCard.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/ExpenseDateRelation.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/FinancialHealth.kt, app/src/main/java/br/com/tick/teira/ui/screens/configuration/ConfigurationScreen.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/ExpensesGrid.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/QuickExpenseBar.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/WalletScreen.kt, app/src/main/java/br/com/tick/teira/ui/theme/Spacing.kt, app/src/main/java/br/com/tick/teira/ui/theme/Theme.kt
- Added a sizing extension to remove hardcoded sizes
=> [12] - Sizing Extension

app/src/main/java/br/com/tick/teira/MainActivity.kt, app/src/main/java/br/com/tick/teira/ui/datasource/databases/ExpenseDao.kt, app/src/main/java/br/com/tick/teira/ui/datasource/databases/TeiraDatabase.kt, app/src/main/java/br/com/tick/teira/ui/datasource/databases/entities/Category.kt, app/src/main/java/br/com/tick/teira/ui/datasource/domain/ExpenseCategory.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpenseRepository.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpensesRepositoryImpl.kt, app/src/main/java/br/com/tick/teira/ui/elements/TextFields.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/CategoryRank.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/models/MostExpensiveCategory.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/usecases/GetMostExpensiveCategories.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/QuickExpenseBar.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/WalletScreen.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/models/ExpenseCard.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/models/ExpenseCategory.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/usecases/CreateExpensesCards.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/viewmodels/QuickExpenseBarViewModel.kt, app/src/main/res/drawable/ic_add.xml
- Found a way to include category to expense on a database perspective
- Now user can create a Category separately from the Expense
- Dialogs and overall layouts were left behind
- Domain models should be thought through better
- Still not sure about flows being collected and emitted with different types
=> [13] - Adding Category to Expense

app/src/main/java/br/com/tick/teira/ui/datasource/databases/CategoryDao.kt, app/src/main/java/br/com/tick/teira/ui/datasource/databases/ExpenseDao.kt, app/src/main/java/br/com/tick/teira/ui/datasource/databases/TeiraDatabase.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/CategoryRepository.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/CategoryRepositoryImpl.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpenseRepository.kt, app/src/main/java/br/com/tick/teira/ui/datasource/repositories/ExpensesRepositoryImpl.kt, app/src/main/java/br/com/tick/teira/ui/di/DatabaseModule.kt, app/src/main/java/br/com/tick/teira/ui/di/RepositoriesModule.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/ExpenseDateRelation.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/usecases/CalculateFinancialHealthSituation.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/usecases/FetchLastMonthExpenses.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/usecases/GetMostExpensiveCategories.kt, app/src/main/java/br/com/tick/teira/ui/screens/analysis/viewmodels/AnalysisScreenViewModel.kt, app/src/main/java/br/com/tick/teira/ui/screens/configuration/ConfigurationScreen.kt, app/src/main/java/br/com/tick/teira/ui/screens/configuration/states/MonthlyIncomeStates.kt, app/src/main/java/br/com/tick/teira/ui/screens/configuration/viewmodels/ConfigurationScreenViewModel.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/AddNewCategoryDialog.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/ExpensesGrid.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/QuickExpenseBar.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/WalletScreen.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/usecases/CreateExpensesCards.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/viewmodels/ExpensesGridViewModel.kt, app/src/main/java/br/com/tick/teira/ui/screens/wallet/viewmodels/QuickExpenseBarViewModel.kt
Fiz uma leitura do inicio ao fim dos fluxos. Separei o DAO em dois (acho que está certo), coloquei a transformação do dado nos use cases, melhorei os operadores de flow, limpei os VMs e, por ordem, os Composables.
=> [15] - Enhancing Flows and its collectors

build.gradle, sdk/src/main/java/br/com/tick/sdk/database/ExpenseDao.kt, sdk/src/main/java/br/com/tick/sdk/database/entities/Expense.kt, sdk/src/main/java/br/com/tick/sdk/domain/CategorizedExpense.kt, sdk/src/main/java/br/com/tick/sdk/repositories/categorizedexpense/CategorizedExpenseRepository.kt, sdk/src/main/java/br/com/tick/sdk/repositories/categorizedexpense/CategorizedExpensesRepositoryImpl.kt, sdk/src/qa/java/br/com/tick/sdk/repositories/FakeCategorizedExpenseRepository.kt, ui/build.gradle, ui/src/main/java/br/com/tick/ui/screens/analysis/ExpenseDateRelation.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/states/AnalysisGraphStates.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/usecases/CalculateFinancialHealthSituation.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/usecases/FetchLastMonthExpenses.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/usecases/GetMostExpensiveCategories.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/QuickExpenseBar.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/viewmodels/QuickExpenseBarViewModel.kt, ui/src/test/java/br/com/tick/ui/viewmodels/AnalysisScreenViewModelTest.kt, ui/src/test/java/br/com/tick/ui/viewmodels/ExpensesGridViewModelTest.kt
- Graph Library is changed to Vico
- Dates are all now "yyyy-MM-dd"
=> [27] Normalize Logic around dates

app/build.gradle, app/google-services.json, build.gradle, ui/src/main/java/br/com/tick/ui/TeiraScaffold.kt, ui/src/main/java/br/com/tick/ui/core/ButtonElements.kt, ui/src/main/java/br/com/tick/ui/core/QuickExpenseCard.kt, ui/src/main/java/br/com/tick/ui/core/TextFields.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/AnalysisScreen.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/CategoryRank.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/ExpenseDateRelation.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/FinancialHealth.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/states/FinancialHealth.kt, ui/src/main/java/br/com/tick/ui/screens/settings/SettingsScreen.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/AddNewCategoryDialog.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/ExpensesGrid.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/QuickExpenseBar.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/WalletScreen.kt, ui/src/main/java/br/com/tick/ui/theme/Color.kt, ui/src/main/java/br/com/tick/ui/theme/Spacing.kt, ui/src/main/java/br/com/tick/ui/theme/Theme.kt, ui/src/main/res/values/strings.xml, ui/src/main/res/values/strings_settings.xml, ui/src/main/res/values/strings_wallet.xml
- Changed colors
- Fixed UI elements
- Enhanced View layer
- Added crashlytics
=> [28] Remodel of App appearance

ui/src/main/java/br/com/tick/ui/core/TextFields.kt, ui/src/main/java/br/com/tick/ui/screens/settings/SettingsScreen.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/AddNewCategoryDialog.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/QuickExpenseBar.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/viewmodels/QuickExpenseBarViewModel.kt
This is simply nowhere I want it to be. But if I dont move on, I wont do the rest. Sorry future me.
=> [33] Quick fix for TextFields

ui/src/main/java/br/com/tick/ui/core/QuickExpenseCard.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/QuickExpenseBar.kt
Finally the contents are being animated
=> [34] - Animated Content

sdk/src/main/java/br/com/tick/sdk/extensions/LocalDateTimeExtension.kt, ui/build.gradle, ui/src/main/java/br/com/tick/ui/TeiraScaffold.kt, ui/src/main/java/br/com/tick/ui/worker/PeriodicWorker.kt
Finally I normalized the timers to get propper minutes by an api that actually makes sense
=> [35] Fix notifications not being shown

ui/src/main/java/br/com/tick/ui/TeiraScaffold.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/QuickExpenseBar.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/WalletScreen.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/viewmodels/QuickExpenseBarViewModel.kt, ui/src/test/java/br/com/tick/ui/viewmodels/QuickExpenseBarViewModelTest.kt
I got expenses ID all messed up. This will probably give me headaches in the future lol
=> [36] Expense Adition fix

ui/src/main/java/br/com/tick/ui/screens/analysis/ExpenseDateRelation.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/FinancialHealth.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/states/FinancialHealth.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/usecases/FetchLastMonthExpenses.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/usecases/GetMostExpensiveCategories.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/viewmodels/AnalysisScreenViewModel.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/viewmodels/QuickExpenseBarViewModel.kt, ui/src/main/res/values/strings_analysis.xml, ui/src/test/java/br/com/tick/ui/viewmodels/AnalysisScreenViewModelTest.kt
Some visual improvements and also stable implementation of business logic
=> [37] - Analysis screen enhanced

.github/workflows/pull_request_android_test.yml, app/build.gradle
This is the initial setup for Firebase which also included all the work to setup on Firebase itself and Google Clouds
=> [38] Firebase Release

ui/src/main/java/br/com/tick/ui/screens/analysis/AnalysisScreen.kt, ui/src/main/java/br/com/tick/ui/screens/settings/SettingsScreen.kt
- Settings and Analysis pages are now scrollable for smaller devices
=> [48] Making Screens Scrollable

ui/src/main/java/br/com/tick/ui/screens/settings/SettingsScreen.kt
- Added an extra small spacing between monthly income text field and subtitle
=> [49] Spacing in Monthly Income Subtitle

ui/src/main/java/br/com/tick/ui/core/TeiraDropdown.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/MostExpensiveCategory.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/usecases/GetMostExpensiveCategories.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/QuickExpenseBar.kt
- Adding colors on Cards, Categories and ExpensiveCategories
=> [56] Spreading Colors

app/src/main/java/br/com/tick/teira/di/PendingIntentModule.kt, sdk/src/main/java/br/com/tick/sdk/di/Qualifiers.kt, sdk/src/main/java/br/com/tick/sdk/notifications/NotificationCenter.kt, sdk/src/main/java/br/com/tick/sdk/notifications/TeiraNotificationCenter.kt, ui/src/main/java/br/com/tick/ui/worker/PeriodicWorker.kt
- Adding a pending intent to the notification
- Had to expose it through hilt
=> [58] Adding action to notification click

sdk/src/main/java/br/com/tick/sdk/database/ExpenseDao.kt, sdk/src/main/java/br/com/tick/sdk/repositories/categorizedexpense/CategorizedExpenseRepository.kt, sdk/src/main/java/br/com/tick/sdk/repositories/categorizedexpense/CategorizedExpensesRepositoryImpl.kt, sdk/src/qa/java/br/com/tick/sdk/repositories/FakeCategorizedExpenseRepository.kt, ui/src/main/java/br/com/tick/ui/NavigationItem.kt, ui/src/main/java/br/com/tick/ui/TeiraScaffold.kt, ui/src/main/java/br/com/tick/ui/core/GenericStates.kt, ui/src/main/java/br/com/tick/ui/core/TeiraNavigationDrawer.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/MostExpensiveCategory.kt, ui/src/main/java/br/com/tick/ui/screens/history/HistoryScreen.kt, ui/src/main/java/br/com/tick/ui/screens/history/models/HistoryChartEntry.kt, ui/src/main/java/br/com/tick/ui/screens/history/models/MonthlyGroupedExpenses.kt, ui/src/main/java/br/com/tick/ui/screens/history/models/MonthlyMergedExpense.kt, ui/src/main/java/br/com/tick/ui/screens/history/states/ExpensesHistoryGraphStates.kt, ui/src/main/java/br/com/tick/ui/screens/history/states/ExpensesHistoryStates.kt, ui/src/main/java/br/com/tick/ui/screens/history/viewmodels/HistoryScreenViewModel.kt, ui/src/main/java/br/com/tick/ui/screens/shared/CategoryDialog.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/QuickExpenseBar.kt, ui/src/main/java/br/com/tick/ui/screens/wallet/usecases/CreateExpensesCards.kt, ui/src/main/java/br/com/tick/ui/theme/Color.kt, ui/src/main/res/drawable/ic_expand.xml, ui/src/main/res/drawable/ic_history.xml, ui/src/main/res/drawable/ic_menu.xml, ui/src/main/res/drawable/ic_shrink.xml, ui/src/main/res/values/strings.xml, ui/src/main/res/values/strings_history.xml, ui/src/main/res/values/strings_navigation.xml
Ticket: https://trello.com/c/Cpr6dAuz/10-architecture-history
=> [62] History Screen feature

sdk/src/qa/java/br/com/tick/sdk/repositories/FakeUserRepository.kt, ui/src/main/java/br/com/tick/ui/core/TeiraNavigationDrawer.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/AnalysisScreen.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/FinancialHealth.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/MostExpensiveCategory.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/states/MostExpensiveCategoriesStates.kt, ui/src/main/java/br/com/tick/ui/screens/analysis/viewmodels/AnalysisScreenViewModel.kt, ui/src/main/java/br/com/tick/ui/theme/Color.kt, ui/src/main/java/br/com/tick/ui/theme/Spacing.kt, ui/src/main/res/values/strings_analysis.xml, ui/src/test/java/br/com/tick/ui/viewmodels/AnalysisScreenViewModelTest.kt
Fixed most expensive categories and changed color specs
=> [64] Most Expensive Categories Fix
